language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
 matrix:
# - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
# - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
# - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
# - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
 - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
 - DB=pgsql MOODLE_BRANCH=master
# - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
# - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
# - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
# - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
# - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
# - DB=mysqli MOODLE_BRANCH=master
  
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate  
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || true
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  
after_success:
    - bin/php-coveralls -v --exclude-no-stmt
    
before_deploy:
    - if [ "${BOX}" = "yes" ]; then curl -LSs http://box-project.github.io/box2/installer.php | php; fi;
    - if [ "${BOX}" = "yes" ]; then composer config platform.php 2> /dev/null || composer config platform.php 5.5.0; fi;
    - if [ "${BOX}" = "yes" ]; then composer update --no-dev --no-interaction ${COMPOSER_FLAGS}; fi;
    - if [ "${BOX}" = "yes" ]; then php -d phar.readonly=false box.phar build; fi;

deploy:
    provider: releases
    token:
        secure: RvyoncgjY7qxxQj6gDl+socPypw4pGVSi3cPIjl7me6D0qm9/peibmWaTmW3bbnugYTEHF1mEpR8jUKeyHnEyxWG+gWD71KD42ofT22QUxBoKpVxyRMr44gJNCuTlbzvcQwsURRvP9Fkic4oVukpvjnOCifBdlmay+NE31Wjof0=
    file: build/artifacts/php-coveralls.phar
    skip_cleanup: true
    on:
        repo: php-coveralls/php-coveralls
        tags: true
        all_branches: true
        condition: $BOX = yes